steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/electricity-market-price/app', '-f', 'CloudRun.Dockerfile', '.']
images:
- 'gcr.io/electricity-market-price/app'
